In [26]:
import torch

In [27]:
def activation(x):
    """Sigmoid Activation Function
        Arguments
       ------------
       x: torch.tensor
    """
    return 1/(1+torch.exp(-x))
    

In [28]:
##Generate some data
torch.manual_seed(7) #setting the random seed so things are predictable

#features are three random normal variables
features=torch.randn((1,5))

#True weights for our data, random normal variables again
weights=torch.randn_like(features)

#and a true Bias Term
bias =torch.randn((1,1))

In [29]:
## Calculate the output of this network using the weights and bias tensors
y=activation(torch.sum(features*weights)+bias)
print(y)

tensor([[0.1595]])


In [30]:
## Calculate the output of this network using matrix multiplication
y=activation(torch.mm(features,weights.view(5,1))+bias)
print(y)

tensor([[0.1595]])


# Multilayer Networks

In [31]:
## Generate some data
torch.manual_seed(7) #setting the random seed so things are predictable

# Three random variables in features
features=torch.randn((1,3))

# Define the size of each layer in the network
n_input=features.shape[1]
n_hidden=2
n_output=1

# Weights for inputs to hidden layer
W1=torch.randn(n_input,n_hidden)

# Weights for hidden layer to output layer
W2=torch.randn(n_hidden,n_output)

# Bias terms for hidden and output layer

B1=torch.randn(1,n_hidden)
B2=torch.randn(1,n_output)


In [32]:
h = activation(torch.mm(features,W1)+B1)
y = activation(torch.mm(h,W2)+B2)
y

tensor([[0.3171]])